sudo: false
language: python
python:
  - "3.5"
  - "3.6"
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: Typhon66
  password:
    secure: my_secure_password
  on:
    tags: true
    branch: stable