sudo: false
language: python
python:
  - "3.5"
  - "3.6"
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: Typhon
  password: nh2Ru0r8HFjacnnj8gaJh3z1jduuAqLRYKKMzD52GZMm2RXCqi/mMfwkCXqgfDm/nXuIDky7/4dwushEKN3OSup3SiB1l69/QkVSvG+1dKzGYrIkhC0SuXwe4w4hTv+5dS/GLU+QNdzMSyI4+YfQdP9QeFiIOwbDEyn+zzJL3FPAsg4OskyNcJt5gvvkrF5KI1OEHNtQbfPzzAnb03S+wuDPsbKLw64CQeFdP+N9mguo5yh2DslnQeLts8N5qp0bIbqCb5qbOWewuarhBvF4IntbRtNs+RRJO5ZkcN7wIWcIo1VY5KD9Oxh4vIlBM9LjPoezIQQpTBRR50d6eagRKYPo/nqDMCz3qTOJBbvtagMOAFO46TfRbljo8GowDCIWlSX/aivuYN2kVbqBd+kPs4CktjxlxinLrRBjIkBFjpmpsi9yUj6pLwJafcqsYzzMnFWdvLs/A6l/yW5vwzHaSrxuXcjd0PVu26HdoOmib9UPJrilsP4rxMJ9p9Cn0+K7snP3YkCMax8kuC8PAc0GNnUhQJyvDAo/d34XE59klxc7r6P4XTBHxKES+3hPkscs8oXqBXMdrXexoBF55LQIo0EiqCtWJEGhq4h+1mZ/EkmJX7O9rIjh93lgMj+KjtRAwRqzqVldm4ZOLKhgNGoLNa+bgJxfiLynW+irsTHcnB0=
  on:
    tags: true