version: '2'
services:
  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=my_db
      - MYSQL_ROOT_PASSWORD=root
  web:
    depends_on:
      - database
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASS=admin
      - MYSQL_DB=my_db
      - MYSQL_ROOT_PASS=root
      - MYSQL_PORT=3306